# Generated by Django 6.0.1 on 2026-01-09 11:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaneOperator1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poczatek', models.DateTimeField(blank=True, null=True)),
                ('koniec', models.DateTimeField(blank=True, null=True)),
                ('czas', models.IntegerField(blank=True, null=True)),
                ('msisdn1', models.CharField(blank=True, max_length=20, null=True)),
                ('imei1', models.CharField(blank=True, max_length=20, null=True)),
                ('kierunek', models.CharField(blank=True, max_length=50, null=True)),
                ('msisdn2', models.CharField(blank=True, max_length=20, null=True)),
                ('imei2', models.CharField(blank=True, max_length=20, null=True)),
                ('typ', models.CharField(blank=True, max_length=20, null=True)),
                ('rodzaj', models.CharField(blank=True, max_length=20, null=True)),
                ('bts1', models.CharField(blank=True, max_length=100, null=True)),
                ('bts2', models.CharField(blank=True, max_length=100, null=True)),
                ('lac1', models.FloatField(blank=True, null=True)),
                ('cid1', models.FloatField(blank=True, null=True)),
                ('wspolrzedne1', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('azymut1', models.IntegerField(blank=True, null=True)),
                ('kt1', models.IntegerField(blank=True, null=True)),
                ('zasig1', models.FloatField(blank=True, null=True)),
                ('mcc1', models.FloatField(blank=True, null=True)),
                ('mnc1', models.FloatField(blank=True, null=True)),
                ('lac2', models.FloatField(blank=True, null=True)),
                ('cid2', models.FloatField(blank=True, null=True)),
                ('wspolrzedne2', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('azymut2', models.IntegerField(blank=True, null=True)),
                ('kt2', models.IntegerField(blank=True, null=True)),
                ('zasig2', models.FloatField(blank=True, null=True)),
                ('mcc2', models.FloatField(blank=True, null=True)),
                ('mnc2', models.FloatField(blank=True, null=True)),
                ('imsi1', models.CharField(blank=True, max_length=20, null=True)),
                ('imsi2', models.CharField(blank=True, max_length=20, null=True)),
                ('przekierowanie', models.CharField(blank=True, max_length=50, null=True)),
                ('przekier_imei', models.CharField(blank=True, max_length=50, null=True)),
                ('przekier_imsi', models.CharField(blank=True, max_length=50, null=True)),
                ('przekier_bts', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dane Operator1',
                'verbose_name_plural': 'Dane Operator1',
                'db_table': 'dane_operator1',
            },
        ),
    ]
