# Generated by Django 6.0.1 on 2026-01-09 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daneoperator1',
            name='import_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
